### ISSUE TITLE
[PE-D][Tester D] User guide grammar error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-4/tp#102]
The user guide has an grammatical error in the sentence "In the example above, entering name, or others that are partially name like nam sets focus on the name field."

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: dickongwd/ped#2

**Comment by butteredyakiimo** [comment]
Thank you for the feedback. We will rectify this in the UG
