### ISSUE TITLE
[PE-D][Tester E] Symbols in name field

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-4/tp#103]
The name field only allows alphanumeric characters and spaces. But disallowing symbols like /, (), @ can cause inconvenience if the input of the name field is expected to match the legal name of a person. For example in S/O or D/O, XXX @ XXX, etc.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jonasongg/ped#1

**Comment by butteredyakiimo** [comment]
Thank you for the feedback. We will put this under planned enhancements!
