### ISSUE TITLE
[PE-D][Tester E] Find avail command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-4/tp#105]
In the UG, under `stats avail`, it is stated that entering `find avail` before `stats avail` will result in 100% of fosterers being shown as available. But entering `find avail` will result in 0 fosterers shown (while `find available` will correctly show the 2 fosterers that are available. This seems to contradict the UG that says the find command can match as parts of words.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jonasongg/ped#2

**Comment by butteredyakiimo** [comment]
Thank you for the feedback. We will rectify this in the UG
