### ISSUE TITLE
[PE-D][Tester D] Save command works differently for different context

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-4/tp#109]
When I enter the profile view using an `edit` command, using the `save` command after changing a field will return a "edited person" message and stay in the profile view.

In contrast, when I enter the profile view using an `add` command, using the `save` command automatically exits the profile view, which was unexpected.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: dickongwd/ped#4

**Comment by butteredyakiimo** [comment]
Thank you for the feedback. We will add in the rationale for this in theh UG!
