### ISSUE TITLE
[PE-D][Tester E] Complicated invalid message for add

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-4/tp#113]
![image.png](https://raw.githubusercontent.com/jonasongg/ped/main/files/1cd414db-1243-4f2a-871f-01b270f9df4f.png)

Trying to add a fosterer with an invalid combination of availability, animal name, and animal type shows an error message that can sometimes be confusing due to the number of examples given. You might want to split the error message up to only show when each case may occur.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jonasongg/ped#5

**Comment by butteredyakiimo** [comment]
Thank you for the feedback. We will put this under planned enhancements!
