### ISSUE TITLE
[PE-D][Tester E] Long notes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-4/tp#127]
![image.png](https://raw.githubusercontent.com/jonasongg/ped/main/files/0c3409f0-5b10-4abf-bea3-941e33cba91c.png)

Entering a very long notes section makes it such that the user cannot view the entire section at once, and has to edit the notes section to scroll to view everything. You might want to limit the length of the notes section or make it expand with the length of the text

(btw I love the way you implemented your profile page <3)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jonasongg/ped#10

**Comment by butteredyakiimo** [comment]
Thank you for the feedback, we will consider this as a planned enhancement instead!
