### ISSUE TITLE
[PE-D][Tester E] Types of animals

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-4/tp#133]
![image.png](https://raw.githubusercontent.com/jonasongg/ped/main/files/567e607f-0ded-4092-8b3c-1d9f50cb0a0e.png)

The app only accepts dogs and cats as types of animals, might want to allow for all kinds of animals in the animal type field

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jonasongg/ped#13

**Comment by butteredyakiimo** [comment]
Thank you for the feedback, we will put this in planned enhancements!
