### ISSUE TITLE
[PE-D][Tester E] Add command nil fields

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-4/tp#134]
You might want to make it such that fields that are omitted are treated as nil so increase the convenience for the users as they right now have to type a pretty long command for adding a fosterer.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jonasongg/ped#14

**Comment by butteredyakiimo** [comment]
Thank you for the feedback, we will write this in the planned enhancements.
