### ISSUE TITLE
[PE-D][Tester C] Add command prefixes feel too long

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-4/tp#99]
Prefixes like availability, animalType feel too long to be prefixes. Since they're supposed to be short for higher efficiency.
![Screenshot 2023-11-03 at 4.20.22 PM.png](https://raw.githubusercontent.com/Sheeepen/ped/main/files/1f74e6f5-552f-4e4c-acbd-679b51caa01c.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Sheeepen/ped#1

**Comment by butteredyakiimo** [comment]
Thank you for the feedback. We have already put this under planned enhancements!
